# fly.toml app configuration file generated for network-capital-app on 2026-08-09T14:52:20Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'network-capital-app'
primary_region = 'jnb'

[build]
  dockerfile = 'Dockerfile'

  [build.args]
    REACT_APP_BACKEND_URL = ''

[env]
  DB_NAME = 'network_capital'
  SERVE_FRONTEND = 'true'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '25s'
    method = 'GET'
    path = '/api/healthz'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '1gb'
